epochs: 100
early_stopping: 0

show: True
fast: False

augmentations: safe
copy_paste: False

train_image_size: [256, 256]
valid_image_size: [2048, 2048]

downsample: 1

mosaic: False

mixup: False
mixup_a: 0.5
mixup_p: 0.5

loaders:
  train:
    batch_size: ${batch_size}
    num_workers: 8

  valid:
    batch_size: 1
    num_workers: 4
